#pragma once
// Generated by tools/sprite_studio.py — do not hand-edit; use the studio.
#define CAT_OFFSET_X 12
#define CAT_OFFSET_Y 50
#define CAT_ZOOM 1024
#define STAT_CPU_X 5
#define STAT_CPU_Y 5
#define STAT_RAM_X 5
#define STAT_RAM_Y 25
#define STAT_WPM_X 5
#define STAT_WPM_Y 45
#define STAT_TIME_X -5
#define STAT_TIME_Y 5
#define SCREEN_BG_R 255
#define SCREEN_BG_G 255
#define SCREEN_BG_B 255
