#!/usr/bin/env python3
"""Bongo Cat sprite studio: pixel editor + 240x320 display layout.

  python3 tools/sprite_studio.py              # serve http://127.0.0.1:8765
  python3 tools/sprite_studio.py convert-all  # rebuild animations/*.c from PNGs
  python3 tools/sprite_studio.py convert PATH.png --layer face --name wink
"""

from __future__ import annotations

import argparse
import io
import json
import re
import sys
import threading
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse

from PIL import Image

TOOLS = Path(__file__).resolve().parent
sys.path.insert(0, str(TOOLS))
import lvgl_sprite as lv  # noqa: E402

ROOT = lv.repo_root()
STATIC = TOOLS / "sprite_studio"
LAYOUT_JSON = ROOT / "display_layout.json"
LAYOUT_H = ROOT / "display_layout.h"
HOST, PORT = "0.0.0.0", 8765

POSES = {
    "idle": ["body/standardbody1", "face/stock_face", "table/table1", "paws/twopawsup"],
    "left": ["body/standardbody1", "face/stock_face", "table/table1", "paws/leftpawdown"],
    "right": ["body/standardbody1", "face/stock_face", "table/table1", "paws/rightpawdown"],
    "fast": [
        "body/standardbody1",
        "face/happy_face",
        "table/table1",
        "paws/rightpawdown",
        "effects/right_click_effect",
    ],
    "sleep": ["body/standardbody1", "face/sleepy_face", "table/table1", "effects/sleepy2"],
    "blink": ["body/standardbody1", "face/blink_face", "table/table1"],
    "twitch": ["body/bodyeartwitch", "face/stock_face", "table/table1", "paws/twopawsup"],
    "excited": [
        "body/standardbody1",
        "face/excited_face",
        "table/table1",
        "paws/rightpawdown",
        "effects/excited1",
    ],
}


def catalog() -> list[dict]:
    items = []
    for layer, name in lv.SPRITE_CATALOG:
        png = lv.png_path(ROOT, layer, name)
        c = lv.c_path(ROOT, layer, name)
        items.append(
            {
                "id": f"{layer}/{name}",
                "layer": layer,
                "name": name,
                "png": f"/Sprites/{png.relative_to(ROOT / 'Sprites')}",
                "has_png": png.exists(),
                "has_c": c.exists(),
            }
        )
    # extras not in catalog
    sprites_root = ROOT / "Sprites"
    known = {i["png"] for i in items}
    if sprites_root.exists():
        for p in sorted(sprites_root.rglob("*.png")):
            rel = f"/Sprites/{p.relative_to(sprites_root)}"
            if rel in known:
                continue
            layer = p.parent.name
            if layer == "face":
                layer = "face"
            items.append(
                {
                    "id": f"{layer}/{p.stem}",
                    "layer": layer if layer in lv.LAYERS else "body",
                    "name": p.stem,
                    "png": rel,
                    "has_png": True,
                    "has_c": False,
                    "extra": True,
                }
            )
    return items


def default_layout() -> dict:
    if LAYOUT_JSON.exists():
        return json.loads(LAYOUT_JSON.read_text())
    return {
        "cat_offset_x": 12,
        "cat_offset_y": 50,
        "cat_zoom": 1024,
        "cpu": {"x": 5, "y": 5, "show": True},
        "ram": {"x": 5, "y": 25, "show": True},
        "wpm": {"x": 5, "y": 45, "show": True},
        "time": {"x": -5, "y": 5, "show": True},
        "bg": [255, 255, 255],
    }


def write_layout_header(layout: dict) -> None:
    bg = layout.get("bg", [255, 255, 255])
    cpu = layout["cpu"]
    ram = layout["ram"]
    wpm = layout["wpm"]
    time = layout["time"]
    LAYOUT_H.write_text(
        "\n".join(
            [
                "#pragma once",
                "// Generated by tools/sprite_studio.py — do not hand-edit; use the studio.",
                f"#define CAT_OFFSET_X {int(layout['cat_offset_x'])}",
                f"#define CAT_OFFSET_Y {int(layout['cat_offset_y'])}",
                f"#define CAT_ZOOM {int(layout['cat_zoom'])}",
                f"#define STAT_CPU_X {int(cpu['x'])}",
                f"#define STAT_CPU_Y {int(cpu['y'])}",
                f"#define STAT_RAM_X {int(ram['x'])}",
                f"#define STAT_RAM_Y {int(ram['y'])}",
                f"#define STAT_WPM_X {int(wpm['x'])}",
                f"#define STAT_WPM_Y {int(wpm['y'])}",
                f"#define STAT_TIME_X {int(time['x'])}",
                f"#define STAT_TIME_Y {int(time['y'])}",
                f"#define SCREEN_BG_R {int(bg[0])}",
                f"#define SCREEN_BG_G {int(bg[1])}",
                f"#define SCREEN_BG_B {int(bg[2])}",
                "",
            ]
        )
    )


def sanitize_name(name: str) -> str:
    name = re.sub(r"[^A-Za-z0-9_]", "_", name.strip())
    if not name or name[0].isdigit():
        name = "sprite_" + name
    return name[:48]


def decode_png_b64(data_url: str) -> Image.Image:
    header, b64 = data_url.split(",", 1) if "," in data_url else ("", data_url)
    import base64

    raw = base64.b64decode(b64)
    return Image.open(io.BytesIO(raw)).convert("RGBA")


def save_sprite(layer: str, name: str, im: Image.Image) -> dict:
    if layer not in lv.LAYERS:
        raise ValueError(f"unknown layer {layer}")
    name = sanitize_name(name)
    png = lv.png_path(ROOT, layer, name)
    c = lv.c_path(ROOT, layer, name)
    im = im.convert("RGBA")
    if im.size != (lv.SPRITE_W, lv.SPRITE_H):
        im = im.resize((lv.SPRITE_W, lv.SPRITE_H), Image.NEAREST)
    lv.save_indexed_png(im, png)
    lv.convert_png_file(png, c, name)
    return {"png": str(png.relative_to(ROOT)), "c": str(c.relative_to(ROOT)), "name": name, "layer": layer}


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt: str, *args) -> None:
        sys.stderr.write("[%s] %s\n" % (self.log_date_time_string(), fmt % args))

    def _headers_common(self, ctype: str, length: int) -> None:
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(length))
        self.send_header("Cache-Control", "no-store")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")

    def do_OPTIONS(self):
        self.send_response(204)
        self._headers_common("text/plain", 0)
        self.end_headers()

    def _json(self, obj, status=200):
        body = json.dumps(obj).encode()
        self.send_response(status)
        self._headers_common("application/json", len(body))
        self.end_headers()
        self.wfile.write(body)

    def _bytes(self, data: bytes, ctype: str, status=200):
        self.send_response(status)
        self._headers_common(ctype, len(data))
        self.end_headers()
        self.wfile.write(data)

    def _read_json(self) -> dict:
        n = int(self.headers.get("Content-Length") or 0)
        return json.loads(self.rfile.read(n) or b"{}")

    def do_GET(self):
        parsed = urlparse(self.path)
        path = parsed.path
        if path in ("/", "/index.html"):
            html = (STATIC / "index.html").read_bytes()
            return self._bytes(html, "text/html; charset=utf-8")
        if path == "/api/catalog":
            return self._json({"sprites": catalog(), "poses": POSES, "palette": lv.PALETTE, "layers": list(lv.LAYERS)})
        if path == "/api/layout":
            return self._json(default_layout())
        if path.startswith("/Sprites/"):
            rel = path[len("/Sprites/") :]
            fp = (ROOT / "Sprites" / rel).resolve()
            if not str(fp).startswith(str((ROOT / "Sprites").resolve())) or not fp.is_file():
                self.send_error(404)
                return
            return self._bytes(fp.read_bytes(), "image/png")
        self.send_error(404)

    def do_POST(self):
        parsed = urlparse(self.path)
        path = parsed.path
        try:
            payload = self._read_json()
        except json.JSONDecodeError:
            return self._json({"error": "bad json"}, 400)
        try:
            if path == "/api/save":
                im = decode_png_b64(payload["png"])
                info = save_sprite(payload["layer"], payload["name"], im)
                return self._json({"ok": True, **info})
            if path == "/api/new":
                im = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
                info = save_sprite(payload["layer"], payload["name"], im)
                return self._json({"ok": True, **info})
            if path == "/api/import":
                im = decode_png_b64(payload["png"])
                info = save_sprite(payload["layer"], payload["name"], im)
                return self._json({"ok": True, **info})
            if path == "/api/layout":
                LAYOUT_JSON.write_text(json.dumps(payload, indent=2) + "\n")
                write_layout_header(payload)
                return self._json({"ok": True, "header": str(LAYOUT_H.relative_to(ROOT))})
            if path == "/api/convert-all":
                written = [str(p.relative_to(ROOT)) for p in lv.convert_all(ROOT)]
                return self._json({"ok": True, "written": written})
        except Exception as e:
            return self._json({"error": str(e)}, 400)
        self.send_error(404)


def serve(open_browser: bool = True) -> None:
    if not (STATIC / "index.html").exists():
        sys.exit(f"missing {(STATIC / 'index.html')}")
    httpd = ThreadingHTTPServer((HOST, PORT), Handler)
    url = f"http://{HOST}:{PORT}/"
    print(f"Bongo Cat sprite studio  {url}")
    print(f"this machine            http://127.0.0.1:{PORT}/")
    print(f"LAN / other browsers    http://192.168.0.114:{PORT}/")
    print(f"Tailscale               http://100.80.51.30:{PORT}/")
    print(f"repo  {ROOT}")
    if open_browser:
        threading.Timer(0.4, lambda: webbrowser.open(url)).start()
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nstopped")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd")
    sub.add_parser("serve")
    sub.add_parser("convert-all")
    c = sub.add_parser("convert")
    c.add_argument("png")
    c.add_argument("--layer", required=True, choices=lv.LAYERS)
    c.add_argument("--name", default="")
    args = p.parse_args()
    cmd = args.cmd or "serve"
    if cmd == "serve":
        serve()
        return
    if cmd == "convert-all":
        for path in lv.convert_all(ROOT):
            print("wrote", path.relative_to(ROOT))
        return
    if cmd == "convert":
        src = Path(args.png).expanduser().resolve()
        name = sanitize_name(args.name or src.stem)
        im = Image.open(src).convert("RGBA")
        info = save_sprite(args.layer, name, im)
        print(json.dumps(info, indent=2))


if __name__ == "__main__":
    main()
